// <auto-generated />
using System;
using LKvitai.MES.Modules.Shopfloor.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LKvitai.MES.Modules.Shopfloor.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ShopfloorDbContext))]
    [Migration("20260616120011_InitialShopfloor")]
    partial class InitialShopfloor
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("shopfloor")
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LKvitai.MES.Modules.Shopfloor.Domain.Entities.LegacyProductType", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<string>("KindName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("kind_name");

                    b.Property<DateTimeOffset>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_synced_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset?>("RemovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("removed_at");

                    b.HasKey("Code");

                    b.HasIndex("RemovedAt");

                    b.ToTable("legacy_product_types", "shopfloor");
                });

            modelBuilder.Entity("LKvitai.MES.Modules.Shopfloor.Domain.Entities.ProductTypeWorkflowMap", b =>
                {
                    b.Property<string>("LegacyProductTypeCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("legacy_product_type_code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("WorkflowTemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_template_id");

                    b.HasKey("LegacyProductTypeCode");

                    b.HasIndex("WorkflowTemplateId");

                    b.ToTable("product_type_workflow_maps", "shopfloor");
                });

            modelBuilder.Entity("LKvitai.MES.Modules.Shopfloor.Domain.Entities.WorkCenter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("work_centers", "shopfloor");
                });

            modelBuilder.Entity("LKvitai.MES.Modules.Shopfloor.Domain.Entities.WorkStation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("name");

                    b.Property<int?>("WipLimit")
                        .HasColumnType("integer")
                        .HasColumnName("wip_limit");

                    b.Property<Guid>("WorkCenterId")
                        .HasColumnType("uuid")
                        .HasColumnName("work_center_id");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("WorkCenterId");

                    b.ToTable("work_stations", "shopfloor");
                });

            modelBuilder.Entity("LKvitai.MES.Modules.Shopfloor.Domain.Entities.WorkflowTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("GraphJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("graph_json");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("workflow_templates", "shopfloor");
                });

            modelBuilder.Entity("LKvitai.MES.Modules.Shopfloor.Domain.Entities.ProductTypeWorkflowMap", b =>
                {
                    b.HasOne("LKvitai.MES.Modules.Shopfloor.Domain.Entities.LegacyProductType", null)
                        .WithMany()
                        .HasForeignKey("LegacyProductTypeCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LKvitai.MES.Modules.Shopfloor.Domain.Entities.WorkflowTemplate", null)
                        .WithMany()
                        .HasForeignKey("WorkflowTemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LKvitai.MES.Modules.Shopfloor.Domain.Entities.WorkStation", b =>
                {
                    b.HasOne("LKvitai.MES.Modules.Shopfloor.Domain.Entities.WorkCenter", null)
                        .WithMany()
                        .HasForeignKey("WorkCenterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
